/* Generates lookup tables for sin */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <fcntl.h>
#include <unistd.h>
#include <string.h>
#include <math.h>

#define SINE_OUTPUT "util/lookup_tables.S"
static float sin_lookup[360];

#define SECTION_TEXT ".section \".data\"" \
			"// AUTOGENERATED\n\n" \
			"\n" \
			".globl sine_lookup\nsine_lookup:\n"

int main (int argc, char *argv[]) {
	int i, fdout;

	/* calculate sine lookup table */
	for (i = 0; i < 360; i ++)
		sin_lookup[i] = (float) sin(i * 3.14159265 / 180);

	
	fdout = open(SINE_OUTPUT, O_RDWR | O_CREAT,
			S_IRUSR | S_IRGRP | S_IROTH);

	ftruncate(fdout, 0);

	write(fdout, SECTION_TEXT, strlen(SECTION_TEXT));

	for (i = 0; i < 360; i ++) {
		write(fdout, "  .word ", 8);
		dprintf(fdout, "0x%x // %f \n", *(uint32_t *) &sin_lookup[i],
				sin_lookup[i]);
        }

	return 0;
}
