.section ".data"

.align
.globl hello_str
hello_str: .asciz "Hello, Lev!\n"

.align
.globl framebuffer_acquired_str
framebuffer_acquired_str: .asciz "\nFramebuffer acquired!\n"

.align
.globl alphabet_str
alphabet_str: .asciz "\nThe brown fox jumped over the lazy dog. ! ? : <3\n"

.align
.globl procrastination1
procrastination1: .asciz "STOP PROCRASTINATING!\n"

.align
.globl procrastination2
procrastination2: .asciz "Or if you really need to\n"

.align
.globl procrastination3
procrastination3: .asciz "Then take a look at this\n"

.align
.globl procrastination4
procrastination4: .asciz "MOTHERFUCKING RAINBOW\n"

.align
.globl procrastination5
procrastination5: .asciz "NOOT NOOT\n"

/* Game strings */
.align
.globl score_str
score_str: .asciz "Score:"

.align
.globl health_str
health_str: .asciz "Health:"

.align
.globl speed_str
speed_str: .asciz "Speed:"

.align
.globl powerups_str
powerups_str: .asciz "Powerups:"
