/* Generates lookup tables for sin */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <fcntl.h>
#include <unistd.h>
#include <string.h>
#include <math.h>

#define SINE_OUTPUT "tools/lookup_tables.S"
static float sin_lookup[360];
static float cos_lookup[360];

#define SECTION_TEXT ".section \".data\"" \
			"// AUTOGENERATED\n\n" \
			"\n"
#define SINE_BEGIN "\n.balign 16\n.globl sine_lookup\nsine_lookup:\n"
#define COSINE_BEGIN "\n.balign 16\n.globl cosine_lookup\ncosine_lookup:\n"

#define PI 3.14159265

int main (int argc, char *argv[]) {
	int i, fdout;

	/* calculate sine lookup table */
	for (i = 0; i < 360; i ++)
		sin_lookup[i] = (float) sin(i * PI / 180);

	/* calculate cosine lookup table */
	for (i = 0; i < 360; i ++)
		cos_lookup[i] = (float) cos(i * PI / 180);

	
	fdout = open(SINE_OUTPUT, O_RDWR | O_CREAT, 0644);
	ftruncate(fdout, 0);

	/* write beginning */
	write(fdout, SECTION_TEXT, strlen(SECTION_TEXT));

	/* write sine lookup */
	write(fdout, SINE_BEGIN, strlen(SINE_BEGIN));
	for (i = 0; i < 360; i ++)
		dprintf(fdout, "  .word 0x%x // %f \n", *(uint32_t *) &sin_lookup[i],
				sin_lookup[i]);

	/* write cosine lookup */
	write(fdout, COSINE_BEGIN, strlen(COSINE_BEGIN));
	for (i = 0; i < 360; i ++)
		dprintf(fdout, "    .word 0x%x // %f \n", *(uint32_t *) &cos_lookup[i],
				cos_lookup[i]);

	return 0;
}
