#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <fcntl.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#define MAP_OUTPUT "tools/lookup_tables.S"

#define SECTION_TEXT ".section \".data\"" \
      "// AUTOGENERATED\n\n" \
      "\n"
#define MAP_BEGIN "\n.balign 16\n.globl map_triangles\nmap_triangles:\n"

struct triangle {
  float vertex1[4];
  float vertex2[4];
  float vertex3[4]; 
  float padding[4];
} __attribute__ ((packed));

struct model {
  uint32_t num_triangles;
  triangle *triangles;
} __attribute__ ((packed));

char *lookup_component(int id) {
  switch (id) {
    case 1: return "road_straight_0";
    case 2: return "road_straight_45";
    case 3: return "road_straight_90";
    case 4: return "road_straight_135";
    default: return NULL;
  }
}

struct model *get_component_data(char *component) {
  int file = strcat(component, ".pstl");  
  uint32_t *buffer;
  struct stat st;

  /* Open file */
  file = open(argv[1], O_RDONLY);
  fstat(file, &st);
  buffer = malloc(st.st_size);

  if (read(file, buffer, st.st_size) != st.st_size) {
    printf("Error opening component file");
    return 1;
  }

  /* Return as a structure */
  return (void *) buffer;
}

struct model *translate_chunk(char *component, int x, int z) {
  struct model *component_model = get_component_data(component);

  for (int i = 0; i < component_model->num_triangles; i++) {
    component_model->triangles->vertex1[0] += x;
    component_model->triangles->vertex1[2] += z;
  }

  return component_model;
}

int main (int argc, char *argv[]) {
  int file;
  uint8_t *buffer;
  struct stat st;

  /* Open file */

  file = open(argv[1], O_RDONLY);
  fstat(file, &st);
  buffer = malloc(st.st_size);

  if (read(file, buffer, st.st_size) != st.st_size) {
    printf("Error opening map file");
    return 1;
  }

  /* Process file */

  uint32_t file_size = sizeof(uint32_t) +
                       head->num_triangles * sizeof(struct triangle_min);
  uint32_t *out = malloc(file_size);

  int map_width = atoi(strtok(buffer, " "));
  int map_height = atoi(strtok(NULL, " "));
  int chunk_width = atoi(strtok(NULL, " "));
  int chunk_height = atoi(strtok(NULL, " "));
  int chunk_rows = map_width / chunk_width;
  int chunk_columns = map_height / chunk_height;
  int num_chunks = chunk_rows * chunk_columns;

  int num_total_triangles = 0;

  for (int y = 0; y < chunk_columns; y++) {
    for (int x = 0; x < chunk_rows; x++) {
      char *component_str;

      /* Skip all whitespace */
      do {
        component_str = strtok(NULL, " ");
      } while (strcmp(component_str, '\0'));

      /* Get the chunk represented by the current number */
      char *component = lookup_component(atoi(component_str));

      /* Position the component by translating it accordingly */
      model *translated_chunk = translate_chunk(component, x * chunk_width, y * chunk_height);

      /* Place the chunk in the output world file */
      memcpy(out + 1 + num_total_triangles * sizeof(struct triangle),
             translated_chunk->triangles, translated_chunk->num_triangles * sizeof(struct triangle));

      /* Update number of triangles */
      num_total_triangles += translated_chunk->num_triangles;
    }
  }

  out[0] = num_total_triangles;

  /* Output file */
  int fdout;

  fdout = open(argv[2], O_RDWR | O_CREAT, S_IRUSR | S_IRGRP | S_IROTH);
  write(fdout, out, file_size);

  return 0;
}
